/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;
   static const IconData down_circled2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circled2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_dir = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_dir = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_dir = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_big = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_big = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_big = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_big = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_hand = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_hand = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_hand = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_hand = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circled = IconData(0xf0a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circled = IconData(0xf0a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circled = IconData(0xf0aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circled = IconData(0xf0ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_left = IconData(0xf100, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_right = IconData(0xf101, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_up = IconData(0xf102, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_down = IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_left = IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right = IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_up = IconData(0xf106, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_down = IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_circled_left = IconData(0xf137, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_circled_right = IconData(0xf138, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_circled_up = IconData(0xf139, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_circled_down = IconData(0xf13a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xf175, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xf176, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xf177, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xf178, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circled2 = IconData(0xf18e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circled2 = IconData(0xf190, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
